version: '3.9'

services:
  dbt-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt_test_container
    env_file:
      - .env
    working_dir: /app/dbtlearn
    command: sh -c "dbt deps && dbt test"

  docs_serve:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt_docs_container
    env_file:
      - .env
    working_dir: /app/dbtlearn
    command: sh -c "dbt docs generate && dbt docs serve --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    depends_on:
      - dbt-test