version: '3.9'

services:
  dbt-dagster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt_dagster_container
    env_file:
      - .env
    stdin_open: true
    tty: true
    working_dir: /app/dbtlearn