version: '3.9'

services:
  dbt-dagster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt_dagster_container
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    stdin_open: true
    tty: true