version: '3.9'

services:
  dbt-test:
    build:
      context: .
      dockerfile: Dockerfile-sf_1_9_0
    container_name: dbt_test_container
    env_file:
      - .env
    working_dir: /app/dbtlearn
    command: sh -c "dbt deps && dbt debug && dbt test"

  docs-serve:
    build:
      context: .
      dockerfile: Dockerfile-sf_1_9_0
    container_name: dbt_docs_container
    env_file:
      - .env
    working_dir: /app/dbtlearn
    command: sh -c "dbt deps && dbt docs generate && dbt docs serve --port 8080 --host 0.0.0.0"
    ports:
      - "8888:8080"
    depends_on:
      - dbt-test

  dbt-dagster:
    build:
      context: .
      dockerfile: Dockerfile-sf_1_7_1
    container_name: dbt_dagster_container
    env_file:
      - .env
    working_dir: /app/dbt_dagster_project
    command: sh -c "dagster dev --host 0.0.0.0 --port 3000"
    ports:
      - "3333:3000"
    depends_on:
      - dbt-test